// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return android; // Use android config for Linux development
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmdtDYYLToc_-jHfnKM6zKj9ZhfzyxlvU',
    appId: '1:225076234696:web:abbdcd4461dab88d8c18fd',
    messagingSenderId: '225076234696',
    projectId: 'restaurantapp-42166',
    authDomain: 'restaurantapp-42166.firebaseapp.com',
    databaseURL: 'https://restaurantapp-42166-default-rtdb.firebaseio.com',
    storageBucket: 'restaurantapp-42166.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmOw8iRxANswLr8TpcxI4rEej0sDnFFws',
    appId: '1:225076234696:android:33d39e5807566fad8c18fd',
    messagingSenderId: '225076234696',
    projectId: 'restaurantapp-42166',
    databaseURL: 'https://restaurantapp-42166-default-rtdb.firebaseio.com',
    storageBucket: 'restaurantapp-42166.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqNcNzuNlLJOZYTTwwZM9IJs5z9uL6ld0',
    appId: '1:225076234696:ios:ce506cd5a18b508f8c18fd',
    messagingSenderId: '225076234696',
    projectId: 'restaurantapp-42166',
    databaseURL: 'https://restaurantapp-42166-default-rtdb.firebaseio.com',
    storageBucket: 'restaurantapp-42166.firebasestorage.app',
    iosBundleId: 'com.example.demApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqNcNzuNlLJOZYTTwwZM9IJs5z9uL6ld0',
    appId: '1:225076234696:ios:ce506cd5a18b508f8c18fd',
    messagingSenderId: '225076234696',
    projectId: 'restaurantapp-42166',
    databaseURL: 'https://restaurantapp-42166-default-rtdb.firebaseio.com',
    storageBucket: 'restaurantapp-42166.firebasestorage.app',
    iosBundleId: 'com.example.demApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCmdtDYYLToc_-jHfnKM6zKj9ZhfzyxlvU',
    appId: '1:225076234696:web:7c2d46a01aa38bc18c18fd',
    messagingSenderId: '225076234696',
    projectId: 'restaurantapp-42166',
    authDomain: 'restaurantapp-42166.firebaseapp.com',
    databaseURL: 'https://restaurantapp-42166-default-rtdb.firebaseio.com',
    storageBucket: 'restaurantapp-42166.firebasestorage.app',
  );
}